# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with ramalama-0.13.0
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.model.name }}
  labels:
    app: {{ .Values.model.name }}
spec:
  replicas: {{ .Values.model.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.model.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.model.name }}
    spec:
      containers:
        - name: {{ .Values.model.name }}
          image: {{ .Values.model.image }}
          ports:
            - containerPort: {{ .Values.model.port }}
          resources:
            limits:
              nvidia.com/gpu: {{ .Values.model.gpuCount }}
---
apiVersion: v1
kind: Service
metadata:
    name: {{ .Values.model.name }}
spec:
    selector:
        app: {{ .Values.model.name }}
    ports:
    - port: {{ .Values.model.port }}
      targetPort: {{ .Values.model.port }} 

