apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.ragDatabase.name }}
spec:
  serviceName: {{ .Values.ragDatabase.name }}
  replicas: {{ .Values.ragDatabase.replicaCount }}
  selector: 
    matchLabels:
        app: {{ .Values.ragDatabase.name }}
  template:
    metadata:
        labels:
            app: {{ .Values.ragDatabase.name }}
    spec:
#      - name: copy-data
#        image: docker.io/alpine:latest
#        command: ["sh", "-c", "cp -a /data/. /qdrant/"]
#        volumeMounts:
#            - name: qdrant-storage
#              mountPath: /qdrant
#            - name: database
#              mountPath: /data   
      serviceAccountName: my-service-account 
      containers:
      - name: copy-data
        image: docker.io/alpine:latest
        command: ["sh"]
        volumeMounts:
            - name: qdrant-storage
              mountPath: /qdrant
            - name: database
              mountPath: /data
      - name: {{ .Values.ragDatabase.name }}
        image: qdrant/qdrant:latest 
        ports:
        - containerPort: {{ .Values.ragDatabase.port }} 
        volumeMounts:
        - name: database
          mountPath: /rag-db
      volumes:
        - image:
            reference: {{ .Values.ragDatabase.image }}
            pullPolicy: Always
          name: database
  volumeClaimTemplates:
  - metadata:
      name: qdrant-storage 
    spec: 
      accessModes: [ReadWriteOnce]
      resources:
        requests:
          storage: 10Gi
      storageClassName: gp2
---
apiVersion: v1
kind: Service
metadata:
    name: {{ .Values.ragDatabase.name }}
spec:
    clusterIP: None
    selector:
        app: {{ .Values.ragDatabase.name }}
    ports:
    - name: http 
      port: {{ .Values.ragDatabase.port }}
      targetPort: {{ .Values.ragDatabase.port }}

# This will need a configured service account to pull from ECR
# ADD THAT IN
