apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.ragDatabase.name }}
spec:
  serviceName: {{ .Values.ragDatabase.name }}
  replicas: {{ .Values.ragDatabase.replicaCount }}
  selector: 
    matchLabels:
        app: {{ .Values.ragDatabase.name }}
  template:
    metadata:
        labels:
            app: {{ .Values.ragDatabase.name }}
    spec:
      initContainers:
      - name: preload-db
        image: public.ecr.aws/docker/library/alpine:latest
        command:
        - sh
        - -c
        - |
          apk add --no-cache aws-cli curl tar
          curl -LO https://github.com/oras-project/oras/releases/latest/download/oras_1.3.0_linux_amd64.tar.gz
          tar -xvf oras_1.3.0_linux_amd64.tar.gz -C /usr/local/bin oras
          echo "Logging into ECR..."
          aws ecr get-login-password --region $AWS_REGION \
            | oras login --username AWS --password-stdin $ECR_REGISTRY
          echo "Pulling OCI artifact..."
          oras pull {{ .Values.ragDatabase.image }} -o /tmp/db
          ls
          ls tmp
          ls tmp/db
          echo "Copying to PVC..."
          cp -a /tmp/db/. /qdrant/
        env:
        - name: AWS_REGION
          value: "us-east-1"
        - name: ECR_REGISTRY
          value: "620339869704.dkr.ecr.us-east-1.amazonaws.com"
        - name: RAG_DB_IMAGE
      serviceAccountName: my-service-account 
      containers:
      - name: {{ .Values.ragDatabase.name }}
        image: qdrant/qdrant:latest 
        ports:
        - containerPort: {{ .Values.ragDatabase.port }} 
        volumeMounts:
        - name: database
          mountPath: /rag-db
      volumes:
        - image:
            reference: {{ .Values.ragDatabase.image }}
            pullPolicy: Always
          name: database
  volumeClaimTemplates:
  - metadata:
      name: qdrant-storage 
    spec: 
      accessModes: [ReadWriteOnce]
      resources:
        requests:
          storage: 10Gi
      storageClassName: gp2
---
apiVersion: v1
kind: Service
metadata:
    name: {{ .Values.ragDatabase.name }}
spec:
    clusterIP: None
    selector:
        app: {{ .Values.ragDatabase.name }}
    ports:
    - name: http 
      port: {{ .Values.ragDatabase.port }}
      targetPort: {{ .Values.ragDatabase.port }}

# This will need a configured service account to pull from ECR
# ADD THAT IN
