# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with ramalama-0.13.0
apiVersion: apps/v1
kind: Deployment
metadata:
  name: model
  labels:
    app: model
spec:
  replicas: {{ .Values.model.replicaCount }}
  selector:
    matchLabels:
      app: model
  template:
    metadata:
      labels:
        app: model
    spec:
      containers:
        - name: model
          image: {{ .Values.model.image }}
          ports:
            - containerPort: {{ .Values.model.port }}
          resources:
            limits:
              nvidia.com/gpu: {{ .Values.model.gpuCount }}
---
apiVersion: v1
kind: Service
metadata:
    name: model
spec:
    selector:
        app: model
    ports:
    - port: {{ .Values.model.port }}
      targetPort: {{ .Values.model.port }} 

