# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with ramalama-0.13.0
apiVersion: apps/v1
kind: Deployment
metadata:
  name: model
  labels:
    app: model
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model
  template:
    metadata:
      labels:
        app: model
    spec:
      containers:
        - name: model
          image: rlcr.io/ramalama/gemma-3-4b-it:llamacpp-cuda 
          ports:
            - containerPort: 8080
          resources:
            limits:
              nvidia.com/gpu: 1 
# ---
# apiVersion: v1
# kind: Service
# metadata:
#     name: ramalama-svc
# spec:
#     selector:
#         app: ramalama
#     ports:
#         - protocol: TCP
#           port: 8080
#           targetPort: 8080
#     type: LoadBalancer

