name: Deploy Gemma3 Model

on:
  workflow_dispatch: {}

permissions:
    id-token: write
    contents: read
jobs:
  run-rag-builder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login to AWS CLI
        uses: aws-actions/configure-aws-credentials@main
        with:
          role-to-assume: arn:aws:iam::620339869704:role/gcp-github-oidc-trust-policy 
          aws-region: us-east-1

      - name: Update Kubeconfig for EKS
        run: |
          aws eks update-kubeconfig \
            --name gcp \
            --region us-east-1

      - name: Apply Deployment
        run: kubectl apply -f cluster/eks/ramalama.yaml

